version: "3.3"

services:

  web: 
    container_name: api
    build:
      context: ./
      dockerfile: docker/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
    depends_on:
      - postgesql
      - rabbitmq
    restart: always
    tty: true
    # command: /bank_app
    volumes:
      - ./:/app
    networks:
      - bank_app
  
  service: 
    container_name: service
    build:
      context: ./
      dockerfile: docker/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
    depends_on:
      - postgesql
      - rabbitmq
    restart: always
    # tty: true
    command: /bank_app
    volumes:
      - ./:/app
    networks:
      - bank_app
  postgesql:
    image: postgres:12-alpine
    container_name: postgesql
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=auth_db
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - bank_app

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ./rabbitmq/data/:/var/lib/rabbitmq/
        # - ./rabbitmq/log/:/var/log/rabbitmq/
    networks:
        - bank_app

networks:
  bank_app:
    driver: bridge