server:
  AppVersion: 1.0.0
  Port: :5000
  
postgres:
  PostgresqlHost: postgesql
  PostgresqlPort: 5432
  PostgresqlUser: postgres
  PostgresqlPassword: postgres
  PostgresqlDbname: auth_db
  PostgresqlSslmode: false
  PgDriver: pgx

rabbit:
  RabbitHost: rabbitmq
  RabbitPort: 5672
  RabbitUser: guest
  RabbitPassword: guest