postgres:
  PostgresqlHost: localhost
  PostgresqlPort: 5432
  PostgresqlUser: postgres
  PostgresqlPassword: postgres
  PostgresqlDbname: auth_db
  PostgresqlSslmode: false
  PgDriver: pgx

rabbit:
  RabbitHost: localhost
  RabbitPort: 5672
  RabbitUser: guest
  RabbitPassword: guest
  Queue: task_queue
  