server:
  AppVersion: 1.0.0
  Port: :5000
  QueueOut: task_queue_1
  OueueIn: task_queue_2
  Mode: Development
  CtxTimeoutBroker: 10
  JwtSecretKey: MyBestSecuredKey

logger:
  Development: true
  DisableCaller: false
  DisableStacktrace: false
  Encoding: json
  Level: info

postgres:
  PostgresqlHost: localhost
  PostgresqlPort: 5432
  PostgresqlUser: postgres
  PostgresqlPassword: postgres
  PostgresqlDbname: auth_db
  PostgresqlSslmode: false
  PgDriver: pgx

rabbit:
  RabbitHost: localhost
  RabbitPort: 5672
  RabbitUser: guest
  RabbitPassword: guest
  