server:
  AppVersion: 1.0.0
  Port: :5000
  QueueOut: task_queue_1
  QueueIn: task_queue_2
  Mode: Development
  CtxTimeoutBroker: 10
  JwtSecretKey: MyBestSecuredKey
  JwtExpire: 10

logger:
  Development: true
  DisableCaller: false
  DisableStacktrace: false
  Encoding: console
  Level: info

postgres:
  PostgresqlHost: 127.0.0.1
  PostgresqlPort: 5432
  PostgresqlUser: postgres
  PostgresqlPassword: postgres
  PostgresqlDbname: auth_db
  PostgresqlSslmode: false
  PgDriver: pgx

rabbit:
  RabbitHost: 127.0.0.1
  RabbitPort: 5672
  RabbitUser: guest
  RabbitPassword: guest
  